name: jjspot_api
description: A new Flutter package project.
version: 0.0.1


environment:
  sdk: ">=3.1.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  appwrite: ^11.0.0
  dart_mappable: ^4.2.0
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  mime: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  dart_mappable_builder: ^4.2.0

flutter:
