// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';

// Will be generated by dart_mappable
part 'lat_lng_model.mapper.dart';

@MappableClass()
class LatLngModel with LatLngModelMappable {
  final double latitude;
  final double longitude;

  LatLngModel({
    required this.latitude,
    required this.longitude,
  });
}
