// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';
import 'package:jjspot_api/src/models/lat_lng_model.dart';

// Will be generated by dart_mappable
part 'location_model.mapper.dart';

@MappableClass()
class LocationModel with LocationModelMappable {
  final String name;
  final String description;
  final List<String> images;
  final String address;
  final LatLngModel latLng;

  LocationModel({
    required this.name,
    required this.description,
    required this.images,
    required this.address,
    required this.latLng,
  });
}
